
INSERT INTO `Categorias` VALUES (1,'Arquitectura','Habilidades para diseñar, dirigir y construir proyectos arquitectónicos.'),(2,'Contablidad/Finanzas','Actividades para mantener oportuna y correcta la aplicación del sistema contable y presupuestal.'),(3,'Computacion/TI','Trabajos de capturistas, manejo de paqueteria de software, diseño de redes.'),(4,'Ingenieria electronica','Trabajos con aplicación en la industria.'),(5,'Recursos Humanos','Administración de nóminas, pagas extra de los empleados'),(6,'Servicio y atencion al cliente','Actividades relacionadas con ofrecer servicios y atencion a los clientes.'),(7,'Logistica/transportes','Trabajos relacionados con capacidad de observación.'),(8,'Desarrollo de software','Profesionistas capaces de analizar, diseñar y mejorar estratégicamente proyectos de sistemas de software.'),(9,'Diseño','Crear conceptos visuales para publicidad'),(10,'Comunicaciones','Profesionales que se encargan de escribir las noticias'),(11,'Mercadotecnia','Investigación de mercados, programación y desarrollo del producto.'),(12,'Ventas','Habilidades para supervisar y dirigir las actividades de una oficina o de un departamento de Ventas.'),(13,'Publicidad','Habilidadeds para planificar, dirigir y coordinar.'),(14,'Gerencia/Administracion','Profesionistas capaces para programar, organizar, dirigir, controlar y supervisar las actividades de personal.'),(15,'Educación','Funciones de docencia de carácter profesional.'),(16,'Blockchain y Bitcoin','Trabajos relaciondos con Bitcoin, Blockchain.');

INSERT INTO `Usuarios` VALUES (1,'ivanetinajero@gmail.com','2019-05-25','Ivan Tinajero','12345',1,'itinajero'),(2,'marisol_caniega@gmail.com','2019-05-25','Marisol Caniega','12345',1,'mcaniega');

INSERT INTO `Perfiles` VALUES (1,'SUPERVISOR'),(2,'ADMINISTRADOR'),(3,'USUARIO');

--INSERT INTO `users` VALUES ('luis','{noop}luis123',1),('marisol','{noop}mari123',1);

INSERT INTO `UsuarioPerfil` VALUES (1,2),(1,3),(2,1),(2,2),(2,3);

INSERT INTO `Vacantes` (id, nombre, idCategoria, fecha, descripcion, salario, status, destacado, imagen, detalles ) VALUES (1,'Administrador de datos en la nube ',3,'2019-06-06','Únete al Socio Logístico con mayor presencia en México, Soft Technologies te invita a formar parte de su gran equipo de trabajo como Administrador de datos en la nube.',20000,'Aprobada',1,'logo2.png','<p><span style=\"color: #0000ff;\"><strong>REQUISITOS</strong></span></p>\r\n<p>Escolaridad: Lic. trunca o pasante en Ing en Sistemas '),(3,'Tesorero - Villa Linch ',3,'2019-06-06','Se requiere contar con título Contador Público Nacional o estudiante avanzado, experiencia comprobable de 3 años desempeñando funciones similares, sólidos conocimientos en paquete office',20000,'Aprobada',1,'logo1.png','<p><span style=\"color: #0000ff;\"><strong>REQUISITOS</strong></span></p>\r\n<p>Escolaridad: Lic. trunca o pasante en Ing en Sistemas '),(2,'Analista de Tesoreria - Villa Bosch ',3,'2019-06-06','Gestionar de manera eficiente los fondos de la Compañía, manteniendo una excelente relación con los bancos en busca de mejores resultados en cuanto a toma de financiación o inversiones. Efectiva realización y control del cash flow..',20000,'Aprobada',1,'logo1.png','<p><span style=\"color: #0000ff;\"><strong>REQUISITOS</strong></span></p>\r\n<p>Escolaridad: Lic. trunca o pasante en Ing en Sistemas ');


INSERT INTO `Solicitudes` VALUES (1,'EKFP0YBSmiguel.pdf','Buenas tardes. Envío mi Curriculum Vitae para aplicar para esta oferta de trabajo!','2019-06-19',2,1);